#######################################################
# 
# Cliente.py
# Python implementation of the Class Cliente
# Generated by Enterprise Architect
# Created on:      14-sep-2013 11:50:32 a.m.
# Original author: Victor
# 
#######################################################


class Cliente:

    def __init__(self, nombre = 'Sin Nombre'):
        self._nombre = nombre
        return
